### ISSUE TITLE
Type definition errors

### ISSUE THREAD

**Issue by Vinnl** [linkeddata/rdflib.js#369]
Since #356, rdflib ships a TypeScript type defintion file `index.d.ts` that refers to other files in the same directory (i.e. it contains statements like `import BlankNode from './blank-node'; import Collection from './collection'; // etc.`), but those files are not generated. This results in TypeScript compilation errors for downstream projects:

```
node_modules/rdflib/lib/index.d.ts(1,23): error TS7016: Could not find a declaration file for module './blank-node'. '/home/travis/build/solid/solid-ui/node_modules/rdflib/lib/blank-node.js' implicitly has an 'any' type.

node_modules/rdflib/lib/index.d.ts(2,24): error TS7016: Could not find a declaration file for module './collection'. '/home/travis/build/solid/solid-ui/node_modules/rdflib/lib/collection.js' implicitly has an 'any' type.

# etc.
```

/cc @joepio

**Comment by joepio** [comment]
#363 should fix this, includes many types. I'll modify the `.gitignore` in a future PR.

**Comment by Vinnl** [comment]
Make sure that it's `.npmignore`, not `.gitignore` :) `git revert c097d1a4797a22724e13f178461377a608637e8e` should be sufficient.

**Comment by joepio** [comment]
Gotcha!

**Comment by mrkvon** [comment]
When installing rdflib v1.0.6 in a typescript project, I get:

```
error TS7016: Could not find a declaration file for module 'rdflib'. '[path/to]/node_modules/rdflib/lib/index.js' implicitly has an 'any' type.
  Try `npm install @types/rdflib` if it exists or add a new declaration (.d.ts) file containing `declare module 'rdflib';`
```

Since the [@types/rdflib](https://www.npmjs.com/package/@types/rdflib) was deprecated, the available options are to declare the module manually or install `@types/rdflib@0.20.1` which may be out of date.

Are there any other solutions available at the moment?

**Comment by Vinnl** [comment]
@mrkvon They shouldn't have been deprecated yet, see https://github.com/DefinitelyTyped/DefinitelyTyped/pull/42044

You can either attempt to install an earlier version of those type definitions, wait until my PR at DT has been accepted, or use the prerelease version of rdflib (`npm install rdflib@next`) at your own risk.

**Comment by ludwigschubi** [comment]
is this fixed yet?

**Comment by Vinnl** [comment]
@ludwigschubi yes, this should have been fixed - the release with TS support was 1.0.7 IIRC. I guess it's probably better for you to report a separate bug that can focus wholly on your issue - I'll close this one.

**Comment by pduchesne** [comment]
This is still a problem if your TS project has "noImplicitAny=true", because plain js files (e.g. query.js) do not get transpiled to .d.ts .
Here's a PR that works for me : https://github.com/linkeddata/rdflib.js/pull/513 .

**Comment by Jeronimo59** [comment]
Hello,

I am trying to use rdflib (version 2.2.32) with Typescript, and I cannot get it to work.
Could that be the same type declaration issue ?

```
import rdf from 'rdflib';

const store = rdf.graph();  => throws 'Cannot read properties of undefined (reading \'graph\')'
```

I tried setting "noImplicitAny" to 'false' in tsconfig.json, but it didn't solve the issue.

Apologies in davance if I am missing the obvious...
